// <auto-generated />
namespace BLL.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change1940 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change1940));
        
        string IMigrationMetadata.Id
        {
            get { return "202106071141186_change1940"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
